#![allow(unused_imports)]
use soroban_sdk::{contracterror, contracttype, Address, Bytes, String, Vec};

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ContractError {
    AlreadyInitialized = 1,
    Unauthorized = 2,
    DuplicateAgentId = 3,
    AgentNotFound = 4,
    InvalidAgentId = 5,
    InvalidInput = 6,
    AgentLeased = 7,
    OverflowError = 8,
    SameAddressTransfer = 9,
    NotOwner = 10,
    InvalidAmount = 11,
    NotEnoughBalance = 12,
    AlreadyExists = 13,
    InvalidMetadata = 14,
    OracleError = 15,
    RateLimitExceeded = 16,
    // Bridge errors
    BridgeAlreadyInitialized = 100,
    BridgeNotInitialized = 101,
    BridgePaused = 102,
    ChainNotSupported = 103,
    ValidatorSetNotFound = 104,
    InsufficientValidators = 105,
    TooManyValidators = 106,
    InvalidThreshold = 107,
    ValidatorAlreadyApproved = 108,
    ValidatorNotInSet = 109,
    InsufficientApprovals = 110,
    TransactionNotFound = 111,
    TransactionAlreadyCompleted = 112,
    TransactionAlreadyFailed = 113,
    DoubleSpendDetected = 114,
    AmountBelowMinimum = 115,
    AmountExceedsMaximum = 116,
    InsufficientLiquidity = 117,
    InvalidFeeTier = 118,
    FeeExceedsMaximum = 119,
    WrappedAssetNotFound = 120,
    WrappedAssetNotActive = 121,
    InsufficientLockedAssets = 122,
    LiquidityPoolNotFound = 123,
    LiquidityPoolNotActive = 124,
    InvalidLpTokenAmount = 125,
    TimelockNotExpired = 126,
    UnauthorizedValidatorChange = 127,
    DisputeAlreadyResolved = 128,
    DisputeNotFound = 129,
    InvalidTxHash = 130,
    CounterAlreadyExists = 131,
    InvalidDirection = 132,
    // RBAC errors
    RoleEscalationAttempt = 200,
    RoleConflict = 201,
    // Validation errors
    MetadataTooLong = 210,
    CapabilitiesExceeded = 211,
}
